package com.projeto1.demo.reportCard;

import lombok.Builder;
import lombok.Data;
import java.util.List;

@Data
@Builder
public class ReportCardDTO {

    private Long id;

    private Long studentId; // Reference to student ID for data transfer

    private String studentName; // Student name for data transfer

    private Long periodId; // Reference to academic period ID

    private EvaluationType evaluationType; // FIRST_EVALUATION or FINAL_EVALUATION

    private List<AssessmentDTO> assessments; // DTO for assessments part of the report

    private Long studentClassId; // Reference to student class ID

    private Integer OT; // Oral Test grade

    private Integer WT; // Written Test grade

    private Integer finalGrade; // Final grade for the evaluation

    // Getters and Setters will be generated by Lombok
}
