package com.projeto1.demo.reportCard;

import lombok.Builder;
import lombok.Data;
import java.util.List;

@Data
@Builder
public class ReportCardDTO {

    private Long id;

    private Long studentId; // To link with a student

    private String studentName; // Optionally include student name for easier display

    private Long periodId; // To link with a period

    private String periodName; // Optionally include the period name

    private EvaluationType evaluationType; // FIRST_EVALUATION or FINAL_EVALUATION

    private List<AssessmentDTO> assessments; // Assessments as part of the report

    private Long studentClassId; // To link with the student class

    private String studentClassLevel; // Optionally include class level

    private Integer OT; // Oral Test grade

    private Integer WT; // Written Test grade

    private Integer finalGrade; // Final grade for the evaluation

    // Getters and Setters will be generated by Lombok
}
