version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Points to your Dockerfile in the current directory
    container_name: spring_backend2
    ports:
      - "8080:8080"  # Expose the Spring Boot app on port 8080
    environment:
      # Use Azure PostgreSQL database credentials
      SPRING_DATASOURCE_URL: jdbc:postgresql://smartgrades-postgres.postgres.database.azure.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: smartgradesDB
      SPRING_DATASOURCE_PASSWORD: senhaboaDB4*
