package com.projeto1.demo.reportCard;

import lombok.Builder;
import lombok.Data;
import java.util.List;

import org.springframework.data.annotation.ReadOnlyProperty;

import com.projeto1.demo.studentsClass.StudentClassDTOSimplified;
import com.projeto1.demo.user.UserDTOSimplified;

@Data
@Builder
public class ReportCardDTO {

    private Long id;

    @ReadOnlyProperty
    private UserDTOSimplified student; // Student entity reference

    @ReadOnlyProperty
    private StudentClassDTOSimplified studentClass; // Student class entity reference

    private Long studentId; // Link with a student

    private EvaluationType evaluationType; // FIRST_EVALUATION or FINAL_EVALUATION

    private List<AssessmentDTO> assessments; // Assessments in the report card

    private Long studentClassId; // Link with the student class

    private Integer OT; // Oral Test grade

    private Integer WT; // Written Test grade
    
    @ReadOnlyProperty
    private Integer finalGrade;

    private String comments; // Comments about the student

    private Long teacherId;

    @ReadOnlyProperty
    private String teacherName;



    // Getters and Setters (can be generated by Lombok)
}
